// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using Proto.Enums;
using UnityEngine;

namespace Proto.Data
{
    [Serializable]
    public class Room
    {
        public int ID;
        public string Name;
    }

}

